### ISSUE TITLE
Please include a warning

### ISSUE THREAD

**Issue by mubix** [Stealthbits/ServerUntrustAccount#1]
Adding "Authenticated Users" to have `DS-Install-Replica` is a VERY dangerous operation and if a pentest or red team doesn't go well could leave a company exposed in a very extreme way. Please add a warning to your script that doing so allows ANY user in the environment not just this attack vector but many more. 

Thank you,
Rob

**Comment by gerritlansing** [comment]
Hi Rob, a good point. We're going to add the warning and a confirmation to continue.

**Comment by gerritlansing** [comment]
@mubix We've added the warnings and confirmation. Thanks for the nudge on that.

**Comment by mubix** [comment]
Thank you @JoeDibley  / @gerritlansing  for making the change. It's really appreciated.
